# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Test

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/test.yaml"
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/test.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags:
      - "**"
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-${{ matrix.ubuntu-version }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Python 3.6 is only available in the ubuntu-22.04 runner
          - python-version: "3.6"
            ubuntu-version: "20.04"
          - python-version: "3.7"
            ubuntu-version: "22.04"
          - python-version: "3.8"
            ubuntu-version: "22.04"
          - python-version: "3.9"
            ubuntu-version: "22.04"
          - python-version: "3.10"
            ubuntu-version: "22.04"
          - python-version: "3.11"
            ubuntu-version: "22.04"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"

      - run: pip install ".[test]"

      - run: pytest --cov=simpervisor

      # GitHub action reference: https://github.com/codecov/codecov-action
      - uses: codecov/codecov-action@v3
